version: '3.0'

services:
  dzhura:
    image: node:current-alpine@sha256:6f8ae702a7609f6f18d81ac72998e5d6f5d0ace9a13b866318c76340c6d986b2
    read_only: true
    volumes:
      - ".:/usr/src/service"
    working_dir: /usr/src/service
    entrypoint: npm run scan
    environment:
      NODE_ENV: test
      SEED_TABLES: "yes"
      SKIP_REQUEST_LOGGING: "1"
      NO_UPDATE_NOTIFIER: "true"
      MYSQL_DATABASE: test
      MYSQL_HOST: mysql
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest@sha256:ca31f38b6e325ece985d857db7eba1fe59928b4fd83ff8a55cb912c9684b9e43
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_INITDB_SKIP_TZINFO: "1"

  gauntlt:
    image: gauntlt/gauntlt@sha256:bd70c0015b6c9d0d7ea3fa00a71864f6c344365fff13110b96e6dc93fb01bbdc
    volumes:
      - .:/working
    working_dir: /working
    entrypoint: /working/.docker/gauntlt.sh
    depends_on:
      - dzhura
