version: '3.0'

services:
  dzhura:
    image: node:lts-alpine@sha256:88d9d8da697877a4a771a40e5cbc10a12c2ad959e82f3b0f36ef35635e17f693
    read_only: true
    volumes:
      - ".:/usr/src/service"
    working_dir: /usr/src/service
    entrypoint: npm run scan
    environment:
      NODE_ENV: test
      SEED_TABLES: "yes"
      SKIP_REQUEST_LOGGING: "1"
      NO_UPDATE_NOTIFIER: "true"
      MYSQL_DATABASE: test
      MYSQL_HOST: mysql
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      NPM_CONFIG_LOGLEVEL: silent
      NPM_CONFIG_LOGS_MAX: "0"
      HOME: /tmp
    user: node:node
    tmpfs: /tmp
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest@sha256:05b53c3f7ebf1884f37fe9efd02da0b7faa0d03e86d724863f3591f963de632c
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_INITDB_SKIP_TZINFO: "1"

  gauntlt:
    image: gauntlt/gauntlt@sha256:bd70c0015b6c9d0d7ea3fa00a71864f6c344365fff13110b96e6dc93fb01bbdc
    volumes:
      - .:/working
    working_dir: /working
    entrypoint: /working/.docker/gauntlt.sh
    depends_on:
      - dzhura
